# Generated by Django 5.2.7 on 2025-11-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('cierres', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
