# Generated by Django 5.2.7 on 2025-11-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor_oferta', models.CharField(max_length=100)),
                ('corredor_demandante', models.CharField(max_length=100)),
                ('propiedad', models.CharField(max_length=200)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
